name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.5.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  url_launcher: ^6.3.2
  google_fonts: ^6.3.2
  provider: ^6.1.5+1
  flutter_svg: ^2.2.1
  image_picker: ^1.2.0
  go_router: ^16.2.5
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
